### ISSUE TITLE
Add PaNOSC Search API Data Model

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/datagateway-api#264]
**Description**:
Similar to DataGateway API's database backend, the data model should be defined using classes etc. You can see the DB backend modelling of ICAT in `datagateway_api/common/database/models.py`. This should be as simple as using the [data model](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md) defined in the example implementation. We have discussed using [pydantic](https://pydantic-docs.helpmanual.io/) for this which looks like it could be useful.

Within these classes, the relationships between entities need to be defined. In the database backend, SQLAlchemy did this nicely using `Column()`. Obviously we can't use that library in this case, so we should consider how this can be defined. Maybe just defining the fields as listed in the docs will be enough so long as you can validate what values they are set as - I guess Pydantic will help with that.

There should probably be tests to cover each class/entity of the data model, to ensure they are implemented correctly. I guess it needs to be tested that each attribute of an entity can be fetched/set using sensible values?

**Acceptance criteria**:
- [ ] Implement data model like database backend `models.py`
- [ ] Add tests for each class of the data model

**Comment by VKTB** [comment]
The [data model](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md) documentation and the [data models](https://github.com/panosc-eu/search-api/tree/master/common/models) in the example SearchAPI do not seem to be consistent.

**Affiliation**
- The _Field_ cell in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships) is set as `affiliations`. Perhaps this is a mistake given it is referring to the `Member` class and the [`affiliation.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/affiliation.json#L30) has a `members` field?
- The [`affiliation.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/affiliation.json#L10) has an `id` field instead of `pid` as listed in the [_Properties_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#properties). Which one should be used? If `pid` then should it be mandatory because it listed as non-mandatory in the table?

**Dataset**
- The description at the top specifies that `Technique` is optional but the cardinality for it in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-1) is specified as _1,*_. Was this mistaken for `Parameter` because its cardinality is listed as _0,*_?
- The [`dataset.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/dataset.json#L41) has a `document` field rather than `documents` like specified in the [_Relationships_ table]( https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-1). Should it be singular or plural? If singular like in the JSON model file then I guess that the cardinality is wrong in the table? 
- The [`dataset.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/dataset.json#L35) has a `score` field but this is not listed in the [_Properties_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#properties-1). Should the model have a `score` field?

**Document**
- The [`document.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/document.json#L54) has a `score` field but this is not listed in the [_Properties_ table]( https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#properties-2). Should the model have a `score` field?

**File**
- Why is the Field cell for the `Dataset` class in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-3) blank? Does that mean that there should not be a field for this class in this model? If so then why does the [`file.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/file.json#L27) has a `dataset` field?

**Instrument**
- The [`instrument.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/instrument.json#L14) has a `pid` field instead of `id` as listed in the [_Properties_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#properties-4). Which one should be used?
- The [`instrument.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/instrument.json#L27) has a `score` field but this is not listed in the [_Properties_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#properties-4). Should the model have a `score` field?

**Member**
- Why is the _Field_ cell for the `Document` class in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-5) blank? Does that mean that there should not be a field for this class in this model? If so then why does the [`member.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/member.json#L20) has a `document` field?
- The [`member.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/member.json#L30) has an `affiliation` field rather than `affiliations` like specified in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-5). Should it be singular or plural? If singular like in the JSON model file then I guess that the cardinality is wrong in the table?

**Parameter**
- Why is the _Field_ cell for the `Dataset` class in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-6) blank? Does that mean that there should not be a field for this class in this model? If so then why does the [`parameter.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/parameter.json#L33) has a `dataset` field?
- Why is the _Field_ cell for the `Document` class in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-6) blank? Does that mean that there should not be a field for this class in this model? If so then why does the [`parameter.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/parameter.json#L28) has a `document` field?

**Person**
- Why is the _Field_ cell for the `Member` class in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-7) blank? Does that mean that there should not be a field for this class in this model? If so then why does the [`person.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/person.json#L33) has a `members` field?

**Sample**
- The [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-8) lists the `datasets` as a field to this model however the [`sample.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/sample.json) does not have such a field. Should there be a `datasets` field in this model?
- The `pid` field is listed as non-mandatory in the [_Properties_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#properties-8) but it is set as mandatory in the [`sample.json` model file](https://github.com/panosc-eu/search-api/blob/master/common/models/sample.json#L12). Should it be mandatory or not?

**Technique**
- Why is the _Field_ cell for the `Dataset` class in the [_Relationships_ table](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#relationships-9) blank? Does that mean that there should not be a field for this class in this model?

**Comment by MRichards99** [comment]
Thanks for looking at this Viktor, I agree with each of your points/questions. I would also point out there seems to be inconsistencies between cardinalities between entities in the data model. One good example of this is [Document](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#document). This states there is a 0-many relationship to the [Member entity](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md#member), but if you look at that entity, it states there is a 1-1 relationship to Document. This appears to be conflicting and I'm not sure which is correct.
