### ISSUE TITLE
Difference between PANOSC/ESS and search-api filter query parameter

### ISSUE THREAD

**Issue by antolinos** [ral-facilities/datagateway-api#357]
**Description**:
I was looking the PANOSC portal (https://data.panosc.eu) and comparing the most usual queries. As proposed by the UI, when someone searches by "diffraction" the next query is built:
```
https://federated.scicat.ess.eu/api/documents?filter={"query":"diffraction","limit":"50"}
```
However, the equivalent filter query in the `search-api` is:
```
http://127.0.0.1:5000/search-api/documents?filter={"query":"diffraction","limit":"50"}
```

but it returns:
```json
{
  "error": {
    "message": "No valid filter name given within filter query param: query", 
    "name": "FilterError", 
    "statusCode": 400
  }
}
```

I was wondering, should not the both APIs identical? Am I doing something wrong or it is not implemented?

I noted that replacing the query by `where` works in both cases:
```
https://federated.scicat.ess.eu/api/documents?filter={ "where": { "text": "diffraction" }}
http://127.0.0.1:5000/search-api/documents?filter={ "where": { "text": "diffraction" }}
```

Thanks!

**Comment by MRichards99** [comment]
It looks like the `query` query parameter is part of the scoring implementation for PaNOSC. The best example I can find is on the Federated Search Service documentation. The [second example](https://github.com/panosc-eu/panosc-federated-search-service/blob/master/docs/dataset-example-queries-remote-data-sources.md#2-query-datasets-relevant-to-data-beam-retrieve-only-10-best-results) shows an example of what you've seen on the portal. From the explanation given, I believe the `query` query parameter is used for the scoring.

This hasn't been implemented on the ICAT implementation of the search API. It didn't appear in the example implementation (or API definition document) and the scoring was introduced to us at a late stage of us implementing the search API. We would welcome help from yourselves or others from the ICAT collaboration to add this functionality in because I am unsure that we will be able to spare additional capacity on top of what we have already done.

That being said, it does seem `query` is quite important for the search bar on the front page of the portal. I will ask within our team to advise me on any further steps and I'll update this issue if anything of significance comes from that.

**Comment by antolinos** [comment]
As you said, it has been implemented for the scoring. I am looking into that.

**Comment by MRichards99** [comment]
If you're able to expand on what you're looking into in terms of the scoring, that would be much appreciated
